<a href="https://colab.research.google.com/github/sense64/data_viz/blob/main/series_prg01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

s = pd.Series([17000, 10000, 40000, 50000])
print(s[0]) #인덱스로 접근

17000

In [ ]:
import pandas as pd

s = pd.Series([17000, 10000, 40000, 50000],
              index=["메론", "수박", "피자", "와인"])
print(s['피자']) #인덱스로 접근

40000

In [ ]:
print("시리즈 값 : {}.".format(s.values))
print("시리즈 인덱스 : {}" .format(s.values))

시리즈 값 : [17000 10000 40000 50000].
시리즈 인덱스 : [17000 10000 40000 50000]

In [ ]:
#딕셔너리를 이용하여 sales_se 시리즈를 생성
sales={"1월" : 10500, "2월" : 70000, "3월" : 60500, "4월" : 432000, "5월": 500000 } #딕셔너리
sales_se = pd.Series(sales) #딕셔너리 키가 시리즈의 인덱스가 됨
print(sales_se)

1월     10500
2월     70000
3월     60500
4월    432000
5월    500000
dtype: int64

In [ ]:
month_se = pd.Series(["1월", "2월", "3월", "4월", "5월"])
sales_se=pd.Series([10500, 70000, 605600, 432000, 500000])
expense_se=pd.Series([9500, 560000, 505600, 342000, 450000])
df = pd.DataFrame({"월":month_se, "판매":sales_se, "비용":expense_se})
print(df)

    월      판매      비용
0  1월   10500    9500
1  2월   70000  560000
2  3월  605600  505600
3  4월  432000  342000
4  5월  500000  450000

In [ ]:
print("판매금액", df['판매'].mean())
print("최대 비용", df['비용'].max())

판매금액 323620.0
최대 비용 560000

In [11]:
import pandas as pd
df_data = pd.read_excel("/content/drive/MyDrive/ML Lecture/data/sinor_data.xlsx", sheet_name="data")
df_data.head()

,no,Q5A1,Q5A2,Q5A3,Q5A4,Q5A5,Q5A6,Q5A7,Q5,Q8B1,...,Q13,Q14B1,Q14B2,Q14B3,Q14B4,Q14,age,gender,wage,wt_가중치
0,1,2,2,2,3,3,3,3,2.571429,4,...,1.00,2,1,1,1,1.25,2,1,6,0.276925
1,2,2,3,1,3,1,1,1,1.714286,4,...,1.00,1,1,1,3,1.50,1,2,3,2.019244
2,3,3,3,1,4,3,1,1,2.285714,4,...,3.00,3,3,3,3,3.00,1,2,4,0.671010
3,4,2,2,1,2,1,2,1,1.571429,4,...,2.25,2,2,3,2,2.25,2,2,4,1.910782
4,5,3,3,2,3,2,2,2,2.428571,3,...,1.50,1,1,1,1,1.00,2,1,3,0.775390